Increase TLD max length in email validation
palkan/pieces-rails pull request #2
Opened 2017-03-31 12:06 UTC by StanisLove

2017-03-31 12:44 UTC, palkan commented on app/assets/javascripts/pieces.js
> +  utils.email_rxp = /\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,15}\b/i;
Why 15? Any proof-link?

2017-03-31 12:45 UTC, palkan commented on app/assets/javascripts/pieces.js
> +  utils.email_rxp = /\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,15}\b/i;
I mean, maybe we should make it open-ended.

2017-03-31 13:53 UTC, StanisLove commented on app/assets/javascripts/pieces.js
> +  utils.email_rxp = /\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,15}\b/i;
I chose fifteen because, it is the longest at the moment (SANDVIKCOROMANT :) )
Open-ended - is good solution to not have problems in the future.

2017-03-31 13:59 UTC, palkan requested changes

2017-03-31 13:59 UTC, palkan commented on app/assets/javascripts/pieces.js
> +  utils.email_rxp = /\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,15}\b/i;
Then let's change it to open-ended

2017-04-03 11:30 UTC, StanisLove commented
Made force push

2017-04-03 12:20 UTC, palkan approved these changes

2017-04-03 12:20 UTC, merged

2017-04-03 12:23 UTC, palkan commented
Released as 1.0.0